---
- name: Download grafana GPG key
  ansible.builtin.get_url:
    url: "{{ grafana_apt_key_url }}"
    dest: "{{ apt_key_path }}/{{ grafana_package }}.asc"
    mode: '0644'

- name: Add grafana APT repository
  ansible.builtin.apt_repository:
    repo: "{{ grafana_apt_repo }}"
    state: present
    filename: grafana

- name: Update apt cache after adding grafana repo
  ansible.builtin.apt:
    update_cache: yes
  when: grafana_apt_repo is defined

- name: Install grafana package
  ansible.builtin.apt:
    name: "{{ grafana_package }}"
    state: present

- name: Ensure grafana is enabled and started
  ansible.builtin.service:
    name: "{{ grafana_service }}"
    enabled: yes
    state: started