---
- name: Download InfluxData archive compatibility key
  ansible.builtin.get_url:
    url: "{{ influx_apt_key_url }}"
    dest: /tmp/influxdata-archive_compat.key
    mode: '0644'

- name: Dearmor and install InfluxData key into trusted.gpg.d
  ansible.builtin.command: >
    gpg --batch --yes --dearmor
        --output "{{ apt_key_path }}/{{ influx_package }}.gpg"
        /tmp/influxdata-archive_compat.key
  args:
    creates: "{{ apt_key_path }}/{{ influx_package }}.gpg"

- name: Delete temporary InfluxData key file
  ansible.builtin.file:
    name: /tmp/influxdata-archive_compat.key
    state: absent

- name: Add InfluxData APT repository
  ansible.builtin.apt_repository:
    repo: "{{ influx_apt_repo }}"
    filename: influx
    state: present

- name: Update apt cache after adding influxdb repo
  ansible.builtin.apt:
    update_cache: yes
  when: influxdb_apt_repo is defined

- name: Install influxdb package
  ansible.builtin.apt:
    name: "{{ influxdb_package }}"
    state: present

- name: Ensure influxdb is enabled and started
  ansible.builtin.service:
    name: "{{ influxdb_service }}"
    enabled: yes
    state: started